### ISSUE TITLE
Rancher Manager source: Discrepancy between cluster and node metrics

### ISSUE THREAD

**Issue by l-mb** [rancher/telemetry#69]
There are seemingly discrepancies in the data reported:

- the total_mem_mb reported vs the sum of the total memory of the managed nodes (node_memb_mb_total)
- Pricing looked at the vCPU distribution per node distribution and found outliers there too

We need to document what these numbers mean and how the difference can be explained.

This may require talking to the Rancher Manager team to explain the metrics reported or looking at the code for RM.

Pricing also recommended that we ask a few known customers for their telemetry dump and compare the numbers reported versus their known environment. Support might be able to help with this task.

**Comment by jhmarina** [comment]
Most information has been added. There's some information that's missing. Asking in Slack hasn't been successful. @jhmarina got in touch with RM's PM to figure out who to speak to

**Comment by jhmarina** [comment]
Rancher PM got back to us and unfortunately no one in the RM team has any knowledge on the information being sent to Telemetry

**Comment by l-mb** [comment]
More details:

the rancher/telemetry project merely queries the APIs provided by the Go client package to Rancher Manager (`github.com/rancher/rancher/pkg/client/generated/management/v3`).

It sums up the results - especially the memory metric is relevant here - for all clusters under management (via the `Client.Cluster.ListAll` call) and all nodes (`Client.Node.ListAll`). The totals _should_ match, but they do not always.

The questions:

- where is Rancher Manager gathering these metrics from on the backend?
- Can this be attributed to different cluster backends somehow?
- Is it perhaps an artifact of caching or incomplete node/cluster removal?

Since these metrics are also shown by RM in its dashboard, this is not merely a telemetry question.

**Comment by l-mb** [comment]
One attempt at narrowing this down on the observation side: https://github.com/rancher/telemetry/issues/73

**Comment by jhmarina** [comment]
This issue will remain open for the next team managing the Telemetry project.

**Comment by l-mb** [comment]
Closing, repo will be archived.
