### ISSUE TITLE
Look at a lifetime cluster to identify discrepancies

### ISSUE THREAD

**Issue by jhmarina** [rancher/telemetry#73]
## What needs to be done

Look at several clusters (with memory discrepancies) lifetime (list will be provided by @0xavi0) and try to identify what may be causing the discrepancies.

## More information
https://confluence.suse.com/display/RES/2023-01-24+Next+steps+call

**Comment by jhmarina** [comment]
This issue has the csv: https://github.com/rancher/telemetry/issues/74

**Comment by p-se** [comment]
Two causes for this issue have been found and described in the [Rancher Manager Telemetry Owner's Manual](https://confluence.suse.com/display/RES/Rancher+Manager+Telemetry+Owner%27s+Manual)
