### ISSUE TITLE
Investigate returned error from ClusterLogging.ListAll

### ISSUE THREAD

**Issue by p-se** [rancher/telemetry#86]
Investigate why ClusterLoggin.ListAll returns an error at all. Since this appears to be an API request, there might be an issue we need to be aware of and fix. This issue was not introduced in v0.6.0 but detected before that release and changed so that the error does not prevent reports from being sent in v0.6.0.

https://github.com/rancher/telemetry/blob/v0.6.0/collector/cluster.go#L164

[Relates to PR#83](https://github.com/rancher/telemetry/pull/83)

**Comment by l-mb** [comment]
Closing, repo will be archived.
