### ISSUE TITLE
Querying vast amounts of data causes InfluxDB to be overloaded

### ISSUE THREAD

**Issue by p-se** [rancher/telemetry#88]
In Grafana, setting the time span for the telemetry dashboard to a year results in vast amounts of data being loaded from InfluxDB, resulting in the server becoming unresponsive, being killed by Kubernetes and restarted. This results in a ~10 to 15 minute downtime of InfluxDB and appears on Grafana as if the data of the last months to be loaded is missing.

Potentially solutions could be to

- limiting the amount of data able to display in Grafana, if that can be configured on a per dashboard basis, to not affect the ability to query the data in that time frame for other dashboards, or
- adapting the resolution of the data in InfluxDB where the data is being aggregated from the `telemetry` measurement to to other measurements which are then directly queried by Grafana.

**Comment by l-mb** [comment]
Closing, repo will be archived.
